### ISSUE TITLE
[BUG] Невозможно запустить интеграционные тесты правила, пока не задана локализация

### ISSUE THREAD

**Issue by Vasilisa-L** [Security-Experts-Community/vscode-xp#101]
### Is there an existing issue or discussion for this?

- [X] I have searched the existing issues and discussions

### Current Behavior

Тесты не запускаются, потому что не найдены файлы локализации

![image](https://github.com/Security-Experts-Community/vscode-xp/assets/72190607/b3904329-8590-4dd3-9628-66475bb802c0)

### Expected Behavior

Тесты хотя бы запускаются, если нет правила локализации: локализацию хочется создавать после того, как правило готово и все тесты успешно прошли

### Steps To Reproduce

1. Создать новое правило
2. Создать тест
3. Запустить тест
4. Получить ошибку из-за отсутствующей локализации

### Environment

```markdown
- OS:
- VSCode:
- VSCode-XP: 3.3.19
```

**Comment by DmitryOffsec** [comment]
Исправлено в версии 3.3.20
