### ISSUE TITLE
[BUG] Ошибки в complex_key при экспорте контента из MP SIEM 26.0 

### ISSUE THREAD

**Issue by Ideas4Life** [Security-Experts-Community/vscode-xp#118]
### Is there an existing issue or discussion for this?

- [X] I have searched the existing issues and discussions

### Current Behavior

При работе с коробочным контентом от 26.0 версии MP SIEM возникает ошибка с построением графа через vsCode для табличных списков. Проблема заключается в том, что vsCode считает, что, например:
- первое поле комплексного ключа в ТС не может быть индексируемым (rule из Correlation_Types_to_Override, dst_host из Unix_Logon_Sessions, username из Active_External_Sessions, file_hash_sha256 из pt_sandbox_detected_malware);
- одиночное ключевое поле не может иметь "nullable:true" (uri из DMZ_hosts_with_open_ports) - согласен с этим, но как это работает в коробке тогда?
![image](https://github.com/Security-Experts-Community/vscode-xp/assets/47158221/d03c1cfe-9404-422f-975a-918f6e7ad7d3)

### Expected Behavior

Нужно, чтобы vsCode при распаковке корректно интерпретировал параметры полей ТС.

### Environment

```markdown
- OS:
- VSCode:
- VSCode-XP:
```

**Comment by DmitryOffsec** [comment]
Принято. Это баг в SDK Tools, будем заводить его на исправление.

**Comment by DmitryOffsec** [comment]
Баг заведён, ждём устранения.

**Comment by DmitryOffsec** [comment]
Баг исправлен. Таргет в 26.1 версию

**Comment by DmitryOffsec** [comment]
Workaround. Тут могу предложить быстро исправить ручками, у первого поля из _complex_key_ сбросить поле _index_ в _false_
