### ISSUE TITLE
[FEATURE] Возможность запуска интеграционных тестов для нескольких правил одновременно

### ISSUE THREAD

**Issue by bobyboba18** [Security-Experts-Community/vscode-xp#123]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

Было бы удобно иметь возможность выделять несколько правил и запускать для них интеграционные тесты. Это поможет сэкономить немало времени. Полезно, например, когда вносишь несколько однотипных изменений в разные правила (например, меняешь запросы в табличные списки из-за обновления какого-то ТС)

### Solution

Добавить возможность выбирать несколько правил и запускать для них интеграционные тесты

**Comment by DmitryOffsec** [comment]
Фича весьма непростая. Для этого придется дублировать все артефакты сборки для каждого из запущенных тестов. Надо подсобрать для неё достаточно лайков, чтобы мы думали как это можно сделать.

**Comment by dmtazetdinov** [comment]
О, я сразу завел и не увидел, что уже что-то обсуждаете. У меня похожий кейс, но в разрезе пакетов
https://github.com/Security-Experts-Community/vscode-xp/issues/140

**Comment by DmitryOffsec** [comment]
Добавить однократную сборку всех зависимостей выделенных правил с их зависимостями

**Comment by DmitryOffsec** [comment]
Оптимизирована сборка в 3.15.1 (Pre-Release)
