### ISSUE TITLE
[BUG] Интеграционные тесты проходят успешно при ошибке заполнения ТС

### ISSUE THREAD

**Issue by bobyboba18** [Security-Experts-Community/vscode-xp#124]
### Is there an existing issue or discussion for this?

- [X] I have searched the existing issues and discussions

### Current Behavior

При выполнении интеграционного теста с заполнением табличных списков (ТС), если в ТС не передается поле, которое не может быть нулевым, тест завершается успешно. При этом в выходных данных присутствует ошибка (скрин), что ненулевое поле в ТС не было заполнено. Мне кажется, что интеграционный тест в таком случае должен завершаться с ошибкой.

### Expected Behavior

Интеграционный тест должен завершаться с ошибкой

### Steps To Reproduce

1. Создать интеграционный тест с записью в ТС, который необходим для работы правила
2. Не заполнять в тесте поле ТС, которое не может быть нулевым
3. Сохранить, запустить интеграционные тесты.

### Environment

```markdown
- OS: Windows 10
- VSCode: 1.80.0
- VSCode-XP: 3.4.0
```

### Anything else?

![image](https://github.com/Security-Experts-Community/vscode-xp/assets/133251570/fc4d164f-cb19-4672-9413-8094ca0f945c)

**Comment by DmitryOffsec** [comment]
В актуальной релизной версии 3.6.0 не воспроизводится
