### ISSUE TITLE
[FEATURE] Привести к единому порядку кнопки в меню

### ISSUE THREAD

**Issue by g4n8g** [Security-Experts-Community/vscode-xp#128]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

Меню у корреляций:
![image](https://github.com/Security-Experts-Community/vscode-xp/assets/55620804/b79af13d-7873-444b-ac75-242341720a4c)
Меню у обогащений:
![image](https://github.com/Security-Experts-Community/vscode-xp/assets/55620804/ef329772-3a7c-40d4-a419-88257318f749)

### Solution

Предлагаю сделать одинаковое меню при нажатии ПКМ, нервирует когда прыгаешь между правилами

**Comment by DmitryOffsec** [comment]
Реализовано в версии 3.7.2 (Pre-Release)
