### ISSUE TITLE
[BUG] Многочисленные ошибки при успешном прохождении быстрых тестов

### ISSUE THREAD

**Issue by g4n8g** [Security-Experts-Community/vscode-xp#137]
### Is there an existing issue or discussion for this?

- [X] I have searched the existing issues and discussions

### Current Behavior

При запуске корреляционных тестов с условием expect not тест проходит успешно о чем свидетельствует строка "You wanted nothing and you've got nothing!", но после этого появляется куча ошибок.
![image](https://github.com/Security-Experts-Community/vscode-xp/assets/55620804/85923cc3-3a1f-4881-a622-7bc31b4f9a9e)

### Expected Behavior

Должна появиться только строка "You wanted nothing and you've got nothing!"

### Steps To Reproduce

Запуск любого теста с expect not

### Environment

```markdown
- OS: Windows 11 Pro 22H2
- VSCode: 1.81.11
- VSCode-XP: 3.7.3
```

**Comment by DmitryOffsec** [comment]
Исправлено в 3.7.5
