### ISSUE TITLE
[FEATURE] Возможность преждевременной остановки действия "Нормализовать и обогатить"

### ISSUE THREAD

**Issue by g4n8g** [Security-Experts-Community/vscode-xp#139]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

Было бы круто иметь возможность остановить действие "Нормализовать и обогатить" как это можно сделать с интеграционными тестами, так как на устройствах со слабой конфигурацией это действие занимает ощутимое количество времени и иногда запускается по ошибке

### Solution

Добавить фичу :)

**Comment by DmitryOffsec** [comment]
Реализовано в версии 3.13.21 (Pre-Release)
