### ISSUE TITLE
[FEATURE] Выполнение интеграционных тестов для конкретного пакета или все сразу

### ISSUE THREAD

**Issue by dmtazetdinov** [Security-Experts-Community/vscode-xp#140]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

Есть несколько отдельных пакетов, внутри множество различных правил/обогащений, но я не могу выполнить сразу все интеграционные тесты, чтобы убедиться, что все правила корректно работают с другими правилами
Сейчас эти тесты можно выполнять только кликая по каждому из правил и проваливаясь в интеграционные тесты, что жутко неудобно, если у тебя больше 1 правила
![image](https://github.com/Security-Experts-Community/vscode-xp/assets/28824032/0148da08-539c-495c-a3e4-ad7b803c535d)

### Solution

Добавить возможность выполнения сразу ВСЕХ интеграционных тестов в конкретно выбранном пакете
Добавить возможность выполнения сразу ВСЕХ интеграционных тестов

**Comment by DmitryOffsec** [comment]
Будем делать чуть больше чем тут предлагается. Будем проверять прохождение интеграционных тестов, тестов локализаций

**Comment by DmitryOffsec** [comment]
Фича реализована для правил нормализации, корреляции и обогащений, которые видны в дереве. Дальше будем улучшать
