### ISSUE TITLE
[FEATURE] Возможность переопределять таймаут корреляции

### ISSUE THREAD

**Issue by dmtazetdinov** [Security-Experts-Community/vscode-xp#142]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

При множестве корреляций и обогащений выполнение интеграционных тестов отваливается по таймауту тк он жестко зашит в плагине `corrules_graph.json --cr-timeout=180 `

### Solution

Нужно вынести в настройки возможность переопределения этого параметра, чтобы оперативно поменять его при сложных пакетах или вот таких ошибках

**Comment by DmitryOffsec** [comment]
Реализовано, выйдет в версии 3.7.8
