### ISSUE TITLE
[FEATURE] Возможность проверять локализацию в правилах нормализации

### ISSUE THREAD

**Issue by laaral-home** [Security-Experts-Community/vscode-xp#144]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

При разработке большого количества формул нормализации и / или для одной формулы нормализации с большим количеством событий не хватает проверки локализации.

Среди частых "проблем" встречаются:

* Опечатки в токенах в полях заполнения (критерий, шаблон локализации)
* При большом количестве формул нормализации, если формулы была скопирована, то иногда забывают сменить **`id`** по которому должна проходить проверка. Т.е. **`id`** может оказаться от другого ресурса, с которого копировали формулу.

### Solution

Как мне видится, то наиболее простым способом было бы проверять токены, что если они существуют, то ОК, а если нет то каким либо образом уведомлять об этом. Либо выделением, либо в выводе работы скрипта писать, что типа поля **`{datafiedl1}`** не существет.

И таким же образом проверять **`id`** формулы (в самом xp-файле).

**Comment by DmitryOffsec** [comment]
Доступна в версии 3.15.8
