### ISSUE TITLE
[FEATURE] Возможность сделать дубликат правила

### ISSUE THREAD

**Issue by g4n8g** [Security-Experts-Community/vscode-xp#145]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

Было бы удобно создавать копию правила для дальнейшего использования в качестве шаблона

### Solution

Сделать кнопку "Дублировать" при нажатии ПКМ на правило

**Comment by DmitryOffsec** [comment]
Добавлена в версии 3.11.18
