### ISSUE TITLE
[FEATURE] Игнорирование графа локализации

### ISSUE THREAD

**Issue by laaral-home** [Security-Experts-Community/vscode-xp#162]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

При построении графов и отсутствии английской локализации возникает ошибка:

```
[08.11.2023 16:01:18] [Error] showErrorMessage("Ошибка компиляции. Смотри Output.") 
```

Вывод в Output следующий:

```
SIEMJ :: ======================================================================
SIEMJ :: SECTION PROCESSED:  make-loca (BUILD_EVENT_LOCALIZATION)
SIEMJ :: ======================================================================
SIEMJ :: SUBPROCESS CMD:     C:\a\kbt\25.1.4362\build-tools\build_l10n_rules.exe --out=C:\a\tools\graph\packages\langs --inject_buildinfo_version=0.0.0-default c:\a\k\knowledgebase_2023_11_08\packages
SIEMJ :: ----------------------------------------------------------------------
BUILD_EVENT_LOCALIZATION [Err] :: [INFO] Found 94 localization rules - parsing started...
BUILD_EVENT_LOCALIZATION [Err] :: [ERROR] Didn't found "en" localization for the content: C:\a\k\knowledgebase_2023_11_08\packages\...\administrator_added
BUILD_EVENT_LOCALIZATION [Err] :: [ERROR] Not a single "Description" was found for the content: C:\a\k\knowledgebase_2023_11_08\packages\...\administrator_added
BUILD_EVENT_LOCALIZATION [Err] :: [INFO] Elapsed time: 0.141 sec
BUILD_EVENT_LOCALIZATION [Err] :: [ERROR] Failed to build localizations - check errors above
SIEMJ :: -------------------- SUBPROCESS EXIT CODE: 1 --------------------
SIEMJ :: Exiting.
```

### Solution

Возможно ли добавить игнорирование выполнения команды `\build_l10n_rules.exe`, либо оставить это выполнение опциональным

**Comment by DmitryOffsec** [comment]
Привет! Проблема понятна. Есть какие-то идеи по реализации в расширении? 
Иногда хочется собирать все артефакты, а иногда только часть. Хочется избежать необходимости натыкивать нужные артефакты и сделать это более дружелюбно.

**Comment by laaral-home** [comment]
Привет. К сожалению, идей нет, просто мы в своей работе наткнулись на этот момент, и мягко говоря он нас не очень порадовал. 
Понимаю, что так реализовали в PT, но у нас на SIEM это работает, так как есть внутри контент, где "всё включено", а вот при разработке коннекторов (локально) такой особой необходимости в английской локализации нет.

**Comment by DmitryOffsec** [comment]
Реализовано в 3.9.7
