### ISSUE TITLE
[FEATURE] Добавить поле TIME в функцию "коррелировать события"

### ISSUE THREAD

**Issue by dmtazetdinov** [Security-Experts-Community/vscode-xp#170]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

Сейчас при выполнении "коррелировать события" для поиска сработающего правила в итоговое событие не пробрасывается и не заполняется поле time, в результате копирования полученного события в SDK, мы будем получать ошибку
`Mandatory fields are not found in normalized event: time`

### Solution

Добавить и заполнять поле TIME

**Comment by DmitryOffsec** [comment]
Реализовано в 3.11.6
