### ISSUE TITLE
[BUG] Ошибка в обработке ТС

### ISSUE THREAD

**Issue by Ideas4Life** [Security-Experts-Community/vscode-xp#173]
### Is there an existing issue or discussion for this?

- [X] I have searched the existing issues and discussions

### Current Behavior

При формировании ТС через vsCode c помощью UI прописывается поле **userCanEditContent: true**. При компиляции данный параметр обрабатывает не корректно и завершается этот процесс с ошибкой. При этом, если его закомментировать, то ошибка при компиляции исчезает.
![image](https://github.com/Security-Experts-Community/vscode-xp/assets/47158221/79c01f11-14b3-4727-b62f-ecbe39a6ac5f)

### Expected Behavior

данный параметр должен обрабатываться корректно.

### Environment

```markdown
- OS: Windows 11
- VSCode: -
- VSCode-XP: 3.11.9
```

**Comment by DmitryOffsec** [comment]
Исправлено в 3.11.10 (Pre-Release)
