### ISSUE TITLE
[FEATURE] Добавить в метаинфо нормализации дополнительный пункт шаблона

### ISSUE THREAD

**Issue by Kovchunov** [Security-Experts-Community/vscode-xp#198]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

Идея сделать в метаинфе комменты для пояснения события нормализованного. Например, событие "Ошибка выполнения функционального контроля". Сразу не поймешь, что такое функциональный контроль в конкретном софте. Коммент вида

```
#######
# ExpertContext: Функциональный контроль подсистем в Secret Net Studio предназначен для обеспечения гарантии того, что к моменту входа пользователя в операционную систему все ключевые защитные подсистемы загружены и функционируют.
При неуспешном завершении вход в систему разрешается только пользователям из локальной группы администраторов компьютера
#######
```

Как будто бы решает эту проблему

### Solution

при генерации шаблона метаинформации для формулы нормализации создается темплейт, заполняемый экспертом

```
#######
# ExpertContext: 
#######
```

**Comment by DmitryOffsec** [comment]
Эту информацию можно добавить в метаинформацию правила нормализации
