### ISSUE TITLE
[BUG] Модульные тесты для правил корреляции. Проблема с отображением дополнительных expect, отделенных комментариями от первого expect

### ISSUE THREAD

**Issue by sanguis-meus** [Security-Experts-Community/vscode-xp#200]
### Is there an existing issue or discussion for this?

- [X] I have searched the existing issues and discussions

### Current Behavior

При создании модульного теста для правила корреляции (с другими типами правил не проверялось) используются несколько критериев expect, отделенных друг от друга строками #-комментариев с пояснениями (пример ниже).

При повторном открытии теста в окошке "Код теста" отображается только первый из expect.
В случае сохранения - теряем все остальные (неотображаемые в webview) expect. 

При удалении строк комментариев (или переносе выше первого expect) все expect начинают отображаться.

Проверили через PTSIEMSDK_GUI: все дополнительные expect отображаются, при сохранении не теряются.

1. Код теста с последующей потерей expect:

```
# Корреляционная цепочка: (Process_Start_Success)
#
# Последовательность событий на входе коррелятора:
# 1. Запуск утилиты "updater" из директории "/srv/updater/"
expect 1 {"alert.regex_match":"/srv/","correlation_name":"X_07_001_Linux_Run_Process"}
#
# 2. Неуспешный (failure) запуск утилиты "backup_db.sh" из директории "/home/user2/backup/" - без корреляции
expect not {"alert.regex_match":"/home/","correlation_name":"X_07_001_Linux_Run_Process"}
#
# 3. Запуск утилиты "jenkins-gitclient-ssh2602379945152964292.sh-copy" из директории "/var/jenkins/workspace/.../"
expect 1 {"alert.regex_match":"/var/","correlation_name":"X_07_001_Linux_Run_Process"}
```

2. Код теста без разделительных комментариев (expect не теряются):

```
# Корреляционная цепочка: (Process_Start_Success)
#
# Последовательность событий на входе коррелятора:
# 1. Запуск утилиты "updater" из директории "/srv/updater/"
# 2. Неуспешный (failure) запуск утилиты "backup_db.sh" из директории "/home/user2/backup/" - 
без корреляции
# 3. Запуск утилиты "jenkins-gitclient-ssh2602379945152964292.sh-copy" из директории "/var/jenkins/workspace/.../"
#
expect 1 {"alert.regex_match":"/srv/","correlation_name":"X_07_001_Linux_Run_Process"}
expect not {"alert.regex_match":"/home/","correlation_name":"X_07_001_Linux_Run_Process"}
expect 1 {"alert.regex_match":"/var/","correlation_name":"X_07_001_Linux_Run_Process"}
```

### Expected Behavior

Возможность использовать комментарии между секциями expect

### Steps To Reproduce

1. Создать модульный тест правила корреляции с несколькими критериями expect, разделенными между собой строками комментариев.
2. Reload, переоткрыть сохраненный тест => перестали отображаться дополнительные секции expect, отделенные комментариями от первого expect
3. Повторно сохранить тест => из исходного файла test.sc удалены все строки после первого expect

### Environment

```markdown
- OS: Parrot 6.1 (Debian 12)
- VSCode: 1.92.1.24225 (codium)
- VSCode-XP: 3.19.0
```

**Comment by DmitryOffsec** [comment]
На Windows не воспроизводится, надо смотреть на *nix

**Comment by DmitryOffsec** [comment]
Привет! Спасибо за детальное описание проблемы. Сделал фикс в пререлизной сборке, версия 3.19.2. Просьба проверить. Если всё будет работать корректно, перенесу в релизную версию.

**Comment by sanguis-meus** [comment]
> Просьба проверить. Если всё будет работать корректно, перенесу в релизную версию.

Проверил, отрабатывает корректно.
