### ISSUE TITLE
[FEATURE] Отключение автозаполнения ObjectId

### ISSUE THREAD

**Issue by zatrahali** [Security-Experts-Community/vscode-xp#45]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

Сейчас при создании контента поле автоматически заполняется поле ObjectId в metainfo.yaml, что может быть неприятно для коробочных правил, так как предлагаемые идентификаторы с префиксом "PT" будут определяться на CI как "untracked Id" с предложением поправить это руками

### Solution

Так как с новым CI  процессом выдачи идентификаторов контента отпадает необходимость в ручной выдаче идентификаторов, предлагаю сделать автозаполнение опциональным или вовсе убрать его для идентификаторов с префиксом "PT"

### Improvements

Еще меньше ручной работы

**Comment by DmitryOffsec** [comment]
Реализовано, выйдет в версии 3.7.8
