### ISSUE TITLE
[BUG] Неправильный критерий локализации для формул нормализации

### ISSUE THREAD

**Issue by zatrahali** [Security-Experts-Community/vscode-xp#65]
### Is there an existing issue or discussion for this?

- [X] I have searched the existing issues and discussions

### Current Behavior

Сейчас, при создании локализации к формуле нормализации, критерий по дефолту принимает значение correlation_name = ""
![image](https://user-images.githubusercontent.com/41584728/235841020-7b862ea6-634f-4d95-866f-f121212904c8.png)

### Expected Behavior

Критерий для локализации формул нормализации по дефолту заполняется id = "<id из кода формулы нормализации>" (В идеале)
или
Критерий для локализации формул нормализации по дефолту заполняется id = ""

### Steps To Reproduce

1. Создать формулу нормализации
2. ПКМ по созданной формуле - Локализации
3. \+ на Критерий

### Environment

```markdown
- OS: WIN10
- VSCode: 1.77.3
- VSCode-XP:v3.3.2
```

**Comment by DmitryOffsec** [comment]
В версии [v3.3.14](https://github.com/Security-Experts-Community/vscode-xp/releases/tag/v3.3.14) частично исправлено как id="<normalization_name>". Или лучше оставить значение пустым?

**Comment by zatrahali** [comment]
Можно оставить как сейчас, но если не будет сильно противоречить каким-то нормам, то я бы предпочел вообще id="normalization_name", чтобы можно было двойным кликом выделить и CTRL + V название формулы, пока не будет автоматом прокидываться из id в formula.xp

**Comment by DmitryOffsec** [comment]
Предлагаю оставить как есть, когда будем глобальное переделывать вьюшку учтём
