### ISSUE TITLE
[FEATURE] Переработка экранирование кавычек в локализации

### ISSUE THREAD

**Issue by zatrahali** [Security-Experts-Community/vscode-xp#67]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

По стандарту в локализациях в качестве апострофов используются одинарные кавычки `User**'**s account`. Расширение сейчас использование одинарной кавычки в локализации обыгрывает сменой экранирования строки с одинарных кавычек на двойные.   
![image](https://user-images.githubusercontent.com/41584728/235843374-e8aa78c4-d521-4bf0-a862-7227f2f1b932.png)

### Solution

В коробке для экранирования одинарной кавычки используется одинарная кавычка, при этом вся строка остается экранированной одинарными кавычками, хочется, чтобы расширение работало по такому же принципу
![image](https://user-images.githubusercontent.com/41584728/235843804-6b1ecbfd-a9ae-45a8-95b2-484454eb13b6.png)

**Comment by DmitryOffsec** [comment]
Данное поведение обуславливается штатной работой сериализатора объекта в yaml, но единый стиль важно поддержать. @anfinogenov что скажешь?

**Comment by anfinogenov** [comment]
> Данное поведение обуславливается штатной работой сериализатора объекта в yaml, но единый стиль важно поддержать. @anfinogenov что скажешь?

Действительно, нынешняя реализация старается минимально использовать экранирование кавычек и выбирает те, что в строке [встречаются реже](https://prettier.io/docs/en/rationale.html#strings). Если мы хотим всегда использовать одинарные кавычки - доступен костыль вроде того, что мы используем для сохранения целых чисел в строках - [client/src/models/metaInfo/metaInfo.ts#L413](https://github.com/Security-Experts-Community/vscode-xp/blob/develop/client/src/models/metaInfo/metaInfo.ts#L413).
То есть, после сохранения метаинфы на диск менять в ней кавычки на ожидаемые в коробке. На чтение это не повлияет, так как экранирование одинарной кавычки ей самой же допускается в yaml.

Более правильным решением будет изменение настроек сериализатора на использование исключительно одинарных кавычек, но, кажется, используемый нами prettier так [не умеет](https://prettier.io/docs/en/options.html#quotes).

**Comment by DmitryOffsec** [comment]
Надо делать свой сериализатор как обёртку над существующими, ибо нам важен формат для поддержки [memoq](https://github.com/Security-Experts-Community/vscode-xp/issues/4)
