### ISSUE TITLE
[FEATURE] Обновление локализации в интерфейсе расширения вслед за обновлениям файлов локализации

### ISSUE THREAD

**Issue by zatrahali** [Security-Experts-Community/vscode-xp#71]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

Если создать правило локализации (неважно, для корреляции или нормализации), а затем изменить его не в интерфейсе расширения, например, через проводник самого vs code, то локаль в расширении останется нетронутой
А вот если в интерфейсе добавить критерий локализации, то изменения подтянутся, после чего критерий можно удалить
Так же не подтягивается добавление новых критериев локализации и самих локализаций, если они были сделаны не через расширение

### Solution

Хочется чтобы изменения файлов вне расширения подтягивались в интерфейс расширения

### Anything else?

Скорее всего эта фича родственна с https://github.com/Security-Experts-Community/vscode-xp/issues/65#issue-1693457292 

А также, скорее всего, она является спорной, так как странно вести разработку контента как в расширении, так и просто редактируя файлы, пусть и в том же редакторе...

Например, мой кейс - нужно было нагенерировать множество локалей скриптом, удобнее работать сразу с файлами. В расширении эти изменения не отображаются, от чего возникает грусть, если случайно нажать на кнопку "Сохранить"

**Comment by DmitryOffsec** [comment]
В актуально версии если нажать на кнопку обновления дерева, текущая открытое окно с локализацией будет обновлено
