### ISSUE TITLE
[BUG] Формирование kb отдельного пакета

### ISSUE THREAD

**Issue by Ideas4Life** [Security-Experts-Community/vscode-xp#79]
### Is there an existing issue or discussion for this?

- [X] I have searched the existing issues and discussions

### Current Behavior

При формировании kb пакета через vsCode в нем не оказывается никаких правил для импорта в PT KB.
![image](https://github.com/Security-Experts-Community/vscode-xp/assets/47158221/22a19e99-4e2b-4110-bafa-10890eaeba61)

### Expected Behavior

При формировании kb файла отдельного пакета должен формировать файл, который можно импортировать в PT KB для добавления\обновления правил.

### Environment

```markdown
- OS: Windows
- VSCode: 1.78.2
- VSCode-XP: 3.3.13
```

**Comment by DmitryOffsec** [comment]
Если получаемых kb-файл переименовать в zip и посмотреть структуру, то в ней нет никаких правил?
Или в файле kb-есть, но при установке через PTKB они не появляются там?

**Comment by Ideas4Life** [comment]
При переименовании в zip там ничего нет из правил.
![image](https://github.com/Security-Experts-Community/vscode-xp/assets/47158221/eee7da86-732b-4293-b541-fb0aed3f453d)

**Comment by aw350m33d** [comment]
> При переименовании в zip там ничего нет из правил.
> ![image](https://user-images.githubusercontent.com/47158221/238595009-eee7da86-732b-4293-b541-fb0aed3f453d.png)

А это только с каким-то конкретным пакетом или со всеми так?

**Comment by Ideas4Life** [comment]
Пробовал с пользовательским пакетом, который был создан в PTKB и выгружен вместе с коробочным контентом. Затем были внесены изменения и осуществлена попытка создания пакета через vsCode.
На текущий момент для импорта одного пакета в PTKB из общей совокупности коробочных правил и своих приходится:
1. выносить в отдельную папку нужный пакет, ранее созданный в PTKB и выгруженный. Папка, куда идёт перенос, имеет структуру, как у выгруженного и распакованного kb файла, но без коробочного контента.
2. заменять символы конца строк CRLF на LF
3. через kbtools выполнять упаковку пакета
4. успешно импортировать в PTKB

Могу предположить, что пакет формируется не корректно из-за наличия символов конца строк CR дополнительно к LF

**Comment by DmitryOffsec** [comment]
Так и не смогли воспроизвести данную ошибку. Переоткроем если будет воспроизводится на последних версиях.
