### ISSUE TITLE
[BUG] Обработка символов конца строки

### ISSUE THREAD

**Issue by Ideas4Life** [Security-Experts-Community/vscode-xp#80]
### Is there an existing issue or discussion for this?

- [X] I have searched the existing issues and discussions

### Current Behavior

При редактировании контента через расширение в vsCode, в код правил добавляется в конце строк символы CR дополнительно к LF. При этом символы "CR" kb сием не может обработать при импорте (на 24 версии точно не умеет). Возможно стоит при формировании kb для импорта в PT KB удалять данные символы?

### Expected Behavior

Корректная обработка символов конца строки

### Environment

```markdown
- OS: Windows
- VSCode: 1.78.2
- VSCode-XP: 3.3.13
```

**Comment by DmitryOffsec** [comment]
Очень странно, ибо это функционал уже есть в расширении.
Я сейчас проверил на открытых правилах https://github.com/Security-Experts-Community/open-xp-rules/, собрал пакет windows_open_package, переименовал его в zip и посмотрел результирующий код правила.
![image](https://github.com/Security-Experts-Community/vscode-xp/assets/124338543/877c674a-b8c8-4d5d-a8c7-1442313ac814)
Все концы строк содержат только LF.
Проверьте, у вас такой же результат получается.

**Comment by Ideas4Life** [comment]
Я проверяю на выгрузке из PT KB со стенда. При открытии через notepad отредактированного файла символы отображаются. После упаковки через Kbtools и импорта в PT KB отображает ошибку.
Примеры символов.
![image](https://github.com/Security-Experts-Community/vscode-xp/assets/47158221/3101f7c9-9a1b-4fa9-951b-94d78e2b943e)

**Comment by Ideas4Life** [comment]
Можно закрывать, актуально только при импорте в PT KB 24 версии, но протестить нет возможности. В 25+ всё нормально работает.

**Comment by DmitryOffsec** [comment]
> Можно закрывать, актуально только при импорте в PT KB 24 версии, но протестить нет возможности. В 25+ всё нормально работает.

Принято. Если у кого будет встречаться данная проблема с возможность её воспроизведения, тогда переоткроем issue.
