### ISSUE TITLE
[FEATURE] Успешность Unit-теста

### ISSUE THREAD

**Issue by Ideas4Life** [Security-Experts-Community/vscode-xp#81]
### Is there an existing feature request or discussion for this?

- [X] I have searched the existing feature requests and discussions

### Problem

При использовании Unit-тестов для правил нормализации требуется обязательно указывать в столбце "Ожидаемый результат" все поля, которые должны появится в сформированном по правилу событии, чтобы тест считался успешным. Возможно стоит рассмотреть вариант, когда тест считается успешным, если он не противоречит значениям из столбца "Ожидаемые результаты"? 
![image](https://github.com/Security-Experts-Community/vscode-xp/assets/47158221/8560aab7-c7d9-4eea-bc2f-b7e41d8aa329)

### Solution

если мы указали в ожидаемых результатах несколько полей, которые должны иметь определённые значения, то все остальные поля нас не интересуют и в этом случае, если после нормализации заданные поля совпали, то тест успешен, иначе - не успешен. При этом допускается, если в нормализованном событии будет дополнительные поля относительно ожидаемых.

**Comment by aw350m33d** [comment]
На мой взгляд в этом и суть теста нормализации - проверить корректность заполнения всех полей. Таким образом мы проверяем, что весь код нормализации отработал как ожидалось. Поэтому, на мой взгляд, в ожидаемом результате нужно указывать полный вывод.

Но если у пользователей другой подход и видение, то можно внести правки. Давайте обсуждать)

**Comment by Ideas4Life** [comment]
Дело в том, что под одно правило нормализации может подходить много событий. Например, данные события могут отличаться значением одного поля (идентификатор сессии пользователя). И если мы создаём новый юнит-тест, то надо вручную анализировать сырое событие и раскидывать все значения по полям. Порой хочется просто посмотреть, как работает правило нормализации.
Было бы здоровое ещё названия юнит-тестам задавать, чтобы понимать что тестирует этот тест.

**Comment by zatrahali** [comment]
Можно ничего не раскидывать руками, если в ожидаемый результат поместить "{}", то из output можно скопировать нормализованное событие целиком  
![image](https://github.com/Security-Experts-Community/vscode-xp/assets/41584728/92a091c6-0d50-44eb-9441-e4ca49063686)  
  
Согласен, что нужно в ожидаемый результат помещать значение всех таксономических полей, которые заполняет данная формула для данного теста, потом по этим же данным можно писать фильтры для правил корреляции, заполнять проброс полей в on-нах и тд.

**Comment by artemcun** [comment]
Мне кажется, было бы все же здорово для нормализации сделать возможность тестов типа как в SDK GUI, т.е. ты просто пишешь формулу, скармливаешь сырое событие, нажимаешь кнопочку "запуск" и просто смотришь на вывод, без дополнительного окошка "ожидаемый результат" и махинаций с ним.
Но можно и подрасширить эту идею на самом деле (напишу пока тут, если стоит завести отдельный FR - скажите) - сделать упрощенный тест, чтоб в ожидаемом результате можно было просто задавать перечень полей, которые ты ожидаешь чтоб были заполнены, вне зависимости от значения в них.

**Comment by aw350m33d** [comment]
> Мне кажется, было бы все же здорово для нормализации сделать возможность тестов типа как в SDK GUI, т.е. ты просто пишешь формулу, скармливаешь сырое событие, нажимаешь кнопочку "запуск" и просто смотришь на вывод, без дополнительного окошка "ожидаемый результат" и махинаций с ним. Но можно и подрасширить эту идею на самом деле (напишу пока тут, если стоит завести отдельный FR - скажите) - сделать упрощенный тест, чтоб в ожидаемом результате можно было просто задавать перечень полей, которые ты ожидаешь чтоб были заполнены, вне зависимости от значения в них.

**Насчёт первого пункта.** 
В окно Output и так пишется результат нормализации. Он там никак дополнительно не форматируется. 

**Насчёт второго предложения.** 
Насколько я понимаю, описанный функционал актуален в процессе разработки формулы. Когда с каждой новой итерацией добавляются поля в нормализованном событии. Если так, то во время разработки можно смотреть в Output и не обращать внимания на успешность теста. А при завершении разработки формулы скопировать JSON из Output в окошко "Ожидаемый результат". 

Как такой вариант?

**Comment by artemcun** [comment]
> > Мне кажется, было бы все же здорово для нормализации сделать возможность тестов типа как в SDK GUI, т.е. ты просто пишешь формулу, скармливаешь сырое событие, нажимаешь кнопочку "запуск" и просто смотришь на вывод, без дополнительного окошка "ожидаемый результат" и махинаций с ним. Но можно и подрасширить эту идею на самом деле (напишу пока тут, если стоит завести отдельный FR - скажите) - сделать упрощенный тест, чтоб в ожидаемом результате можно было просто задавать перечень полей, которые ты ожидаешь чтоб были заполнены, вне зависимости от значения в них.
> 
> **Насчёт первого пункта.** В окно Output и так пишется результат нормализации. Он там никак дополнительно не форматируется.
> 
> **Насчёт второго предложения.** Насколько я понимаю, описанный функционал актуален в процессе разработки формулы. Когда с каждой новой итерацией добавляются поля в нормализованном событии. Если так, то во время разработки можно смотреть в Output и не обращать внимания на успешность теста. А при завершении разработки формулы скопировать JSON из Output в окошко "Ожидаемый результат".
> 
> Как такой вариант?

Да в целом то неплохой, и по факту сейчас и используемый, просто хотелось чуть меньше итераций и действий для лентяев типа меня :D

**Comment by aw350m33d** [comment]
Описанный упрощённый тест можно сделать. Звучит не сложно. Тем более если это упростит жизнь. 

Просто я пока не понимаю почему это проще. 

Ведь все поля сразу не будут заполнены. Тогда придётся после каждого запуска докидывать поля в ожидаемый список. Но тогда это тоже самое, что докидывать сразу поля со значениями.

Возможно, я никогда не писал много формул. Если ты опишешь чуть подробнее свой воркфлоу, мы сможем придумать как сделать расширение удобнее.

**Comment by artemcun** [comment]
Ну я пока навскидку из потенциально полезных сценариев (помимо лени :)) придумал только два:
1) Как писал кто-то выше, когда у тебя под одну формулу может попадать несколько однотипных событий, и ты хочешь просто проверить заполняемость определенного перечня полей.
2) Быстрый фикс какой-то формулы, когда тебе надо изменить/добавить одно-два поля, и ты хочешь чтоб в результатах теста тебе подсветились только они.

**Comment by DmitryOffsec** [comment]
Мне нравится данный кейс. Пользователь должен иметь возможность проверять те поля, которые ему действительно важны. Если нужны все, то можно после запуска теста просто нажать на кнопку _Обновить ожидаемое событие_

**Comment by DmitryOffsec** [comment]
Давно реализовано, но issue не закрыто
