### ISSUE TITLE
[BUG] Ошибка при импорте пакета с отсутствием английской локализации

### ISSUE THREAD

**Issue by artemcun** [Security-Experts-Community/vscode-xp#84]
### Is there an existing issue or discussion for this?

- [X] I have searched the existing issues and discussions

### Current Behavior

При импорте kb-файла из SIEM, в котором содержатся правила, где нет английской локализации, в дереве контента данные правила не отображаются, и появляется ошибка "Не найден файл английской локализации"

### Expected Behavior

Контент должен отображаться и должна быть возможность вести работу с ним.

### Steps To Reproduce

1. Создать в SIEM правило, в котором будет русская, но не будет английской локализации
2. Экспортировать его
3. Импортировать в VSCode-XP
4. Открыть импортированный пакет в дереве контента

### Environment

```markdown
- OS: Windows 10
- VSCode: 1.78.2
- VSCode-XP: 3.3.16
```

**Comment by artemcun** [comment]
Дополнение: если у правила нет ни русской, ни английской локализации - то оно открывается нормально. Т.е. проблема только там, где есть русская, но нет английской.

**Comment by aw350m33d** [comment]
Спасибо, посмотрим на обработку локализаций. О результатах напишем сюда)

**Comment by DmitryOffsec** [comment]
Исправлено в версии 3.3.19
