### ISSUE TITLE
[BUG] Строгость терминологии

### ISSUE THREAD

**Issue by serg1224** [Security-Experts-Community/vscode-xp#99]
### Is there an existing issue or discussion for this?

- [X] I have searched the existing issues and discussions

### Current Behavior

В текущей версии элементы управления для тестов называются по-разному, нет строгой единой терминологии. В окнах-диалогах названия тестов отсутствуют, сами окна тоже не подписаны.
![module-test](https://github.com/Security-Experts-Community/vscode-xp/assets/67070077/77ef610b-6380-48f7-990d-622984245eac)
![raw-event](https://github.com/Security-Experts-Community/vscode-xp/assets/67070077/eddb629c-73fa-4a3a-960a-f9918bb5c0a7)

### Expected Behavior

- Хотелось бы более конкретных надписей: как на кнопках, так и на окнах-диалогах;
- Хотелось бы более строгой терминологии без синонимов, т.к. каждый синоним заставляет думать о новой сущности;

### Environment

```markdown
- OS: Debian Linux 11
- VSCode: 1.78.2
- VSCode-XP: 3.3.19
```

**Comment by serg1224** [comment]
Было бы удобно, если бы верхние кнопки в окнах-тестах не скролились наверх с текстом событий.

Кнопка [Запустить тест] располагается строго слева, а [Сохранить тест] строго справа, на широком экране правую кнопку можно не заметить. Почему бы кнопки не расположить последовательно слева направо?

Может кнопку [Сохранить тест] вообще упразднить и сделать автосейв?

Если вместо надписей на кнопках будут значки, то UI станет компактнее.

**Comment by serg1224** [comment]
![menu](https://github.com/Security-Experts-Community/vscode-xp/assets/67070077/b3eae35d-bb09-4f58-8728-8ee3b8b70645)

**Comment by serg1224** [comment]
Можно ли в окне тестирования не "портить" сырое (исходное) событие после выбора конверта? Сконвертированное событие можно выводить на отдельную вкладку. Так и видно/понятно лучше и можно будет несколько раз поиграться с выбором подходящего типа конверта.

Поскольку выбор конверта важный шаг, влияющий на результат, я бы эту кнопку не убирал далеко вправо, её там можно просто не заметить.

Предлагаю такой лейаут:
[test]  [save]  [mime][v]

**Comment by serg1224** [comment]
Из UI не всегда понятно можно ли в окно тестирования вставлять несколько событий и каким образом их нужно разделять.

**Comment by serg1224** [comment]
![test-names](https://github.com/Security-Experts-Community/vscode-xp/assets/67070077/96a8f776-c575-44ac-992b-8841cdf6e373)

**Comment by serg1224** [comment]
Модульные (юнит) тесты для корректной работы требуют нажатия кнопки [Сохранить тест]. Иначе срабатывает старый (ранее сохранённый тест). Неочевидное.

**Comment by aw350m33d** [comment]
В ближайшем релизе будут исправлены:
https://github.com/Security-Experts-Community/vscode-xp/issues/99#issue-1737869845
https://github.com/Security-Experts-Community/vscode-xp/issues/99#issuecomment-1573498803
https://github.com/Security-Experts-Community/vscode-xp/issues/99#issuecomment-1573596360

Остальные предложения я бы вынес как отдельные фичи для отслеживания реализации и обсуждения.

**Comment by DmitryOffsec** [comment]
Исправлено в версии 3.3.20
